# Generated by Django 3.1.4 on 2020-12-02 18:20

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('image', models.CharField(max_length=70, null=True)),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('published', models.BooleanField(default=False, null=True)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('group_attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('selling_price', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes', 'group_attributes'], name='api_product_attribu_ba34cd_gin'),
        ),
    ]
